# Generated by Django 2.0.2 on 2018-03-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.BigIntegerField()),
                ('value', models.BigIntegerField()),
            ],
            options={
                'db_table': 'env',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.BigIntegerField()),
                ('value', models.BigIntegerField()),
            ],
            options={
                'db_table': 'sys',
            },
        ),
    ]
