# Generated by Django 2.0.2 on 2018-03-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
        migrations.CreateModel(
            name='SensorsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.BigIntegerField()),
                ('value', models.BigIntegerField()),
                ('sensor', models.ForeignKey(on_delete='CASCADE', to='web_app.Sensor')),
            ],
            options={
                'db_table': 'sensors_data',
            },
        ),
        migrations.CreateModel(
            name='SubSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sub_sys',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.AddField(
            model_name='sensorsdata',
            name='vehicle',
            field=models.ForeignKey(on_delete='CASCADE', to='web_app.Vehicle'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='subsystem',
            field=models.ForeignKey(on_delete='CASCADE', to='web_app.SubSystem'),
        ),
    ]
