# Generated by Django 2.0.2 on 2018-03-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20180319_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
