# Generated by Django 2.0.3 on 2018-03-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20180330_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystem',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='web_app.Vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='web_app.Mission'),
        ),
    ]
