# Generated by Django 2.0.3 on 2018-04-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20180331_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='name',
        ),
        migrations.AddField(
            model_name='mission',
            name='arrival_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Arrival Latitude'),
        ),
        migrations.AddField(
            model_name='mission',
            name='arrival_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Arrival Longitude'),
        ),
        migrations.AddField(
            model_name='mission',
            name='arrival_point',
            field=models.CharField(default='Kazan', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='departure_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Departure Latitude'),
        ),
        migrations.AddField(
            model_name='mission',
            name='departure_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Departure Longitude'),
        ),
        migrations.AddField(
            model_name='mission',
            name='departure_point',
            field=models.CharField(default='Moscow', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit of Measurement'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(max_length=200, verbose_name='Vehicle Type'),
        ),
    ]
