# Generated by Django 2.0.3 on 2018-04-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_auto_20180402_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='subsystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.SubSystem'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Sensor'),
        ),
        migrations.AlterField(
            model_name='sensorsdata',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Vehicle'),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.Vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.Mission'),
        ),
    ]
