# Generated by Django 2.0.3 on 2018-04-07 17:33

from django.db import migrations, models


def change_vehicle_type(apps, schema_editor):
    Vehicle = apps.get_model('web_app', 'Vehicle')
    Vehicle.objects.update(type=None)


class Migration(migrations.Migration):
    dependencies = [
        ('web_app', '0007_auto_20180405_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.RunPython(change_vehicle_type),
    ]
