# Generated by Django 2.0.3 on 2018-04-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_auto_20180407_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='upper_bound',
            field=models.DecimalField(decimal_places=6, default=100.0, max_digits=9, verbose_name='Upper bound of warning threshold'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='lower_bound',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Lower bound of warning threshold'),
        ),
    ]
