# Generated by Django 2.0.3 on 2018-04-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_auto_20180411_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='actual_end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Finish Time'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planned Finish Time'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planned Start Time'),
        ),
    ]
