# Generated by Django 2.0.3 on 2018-04-16 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_concretesubsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_location',
            field=models.CharField(default='Main Station', max_length=200),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_maintenance',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'In maintenance'), ('RESERVED', 'Reserved for mission'), ('MISSION', 'In mission')], default='AVAILABLE', max_length=100),
        ),
        migrations.AlterField(
            model_name='concretesubsystem',
            name='health',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Current Health'),
        ),
        migrations.AlterField(
            model_name='concretesubsystem',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subassies', to='web_app.Vehicle'),
        ),
    ]
