# Generated by Django 2.0.3 on 2018-04-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_auto_20180416_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='web_app.Mission'),
        ),
    ]
