# Generated by Django 2.0.3 on 2018-04-16 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0013_auto_20180416_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('alt', models.BigIntegerField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Mission')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Vehicle')),
            ],
            options={
                'db_table': 'mission_point',
            },
        ),
        migrations.CreateModel(
            name='MissionPointSensorsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='', max_length=255)),
                ('warning', models.BooleanField(default=False)),
                ('value', models.CharField(default='', max_length=255)),
                ('mission_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.MissionPoint')),
            ],
            options={
                'db_table': 'mission_point_sensors_data',
            },
        ),
    ]
