# Generated by Django 2.0.3 on 2018-04-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0014_missionpoint_missionpointsensorsdata'),
        ('web_app', '0011_auto_20180417_0654'),
    ]

    operations = [
    ]
