# Generated by Django 2.0.3 on 2018-04-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prognostics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='pressure',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
    ]
