# Generated by Django 2.0.3 on 2018-04-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_ip', models.CharField(max_length=50)),
                ('broker_http_port', models.CharField(max_length=50)),
                ('broker_ws_port', models.CharField(max_length=50)),
            ],
        ),
    ]
